In [2]:
import pandas as pd
import requests as rs

In [9]:
df = pd.read_csv("Netflix_dataset.csv")
df

,id,title,release_year,runtime,imdb_score,imdb_votes,tmdb_popularity,tmdb_score
0,ts89259,The Queen's Gambit,2020,56,8.6,420100,82.7,8.6
1,ts81120,The Last Dance,2020,50,9.1,115915,27.7,8.2
2,ts235758,Never Have I Ever,2020,28,7.8,47000,47.8,8.2
3,tm863808,My Octopus Teacher,2020,84,8.1,52771,19.3,8.0
4,ts219660,Alice in Borderland,2020,47,7.6,49446,71.0,8.2
5,tm847085,The Social Dilemma,2020,94,7.6,80916,20.4,7.5
6,ts222333,Arcane,2021,41,9.0,186899,106.5,9.1
7,ts220305,Squid Game,2021,55,8.0,426967,361.9,7.8
8,ts223537,Maid,2021,54,8.4,77885,0.6,8.0
9,ts87242,Shadow and Bone,2021,52,7.6,80009,28.1,8.2
10,ts311985,Inside Job,2021,28,7.6,16616,42.4,8.2
11,tm1038686,Bo Burnham: Inside,2021,87,8.7,44074,11.4,8.2
12,ts286731,Komi Can't Communicate,2021,24,7.8,5462,132.8,8.3
13,ts296472,The Chestnut Man,2021,55,7.7,42817,49.6,7.7
14,tm1228854,Bill Burr: Live at Red Rocks,2022,82,7.8,1281,16.1,6.9
15,ts217231,Heartstopper,2022,28,8.7,45476,165.7,9.0
16,ts312082,Alchemy of Souls,2022,80,8.6,878,108.7,8.0
17,ts342732,Our Great National Parks,2022,52,7.9,1684,2.6,7.9
18,ts345200,Borgen - Power & Glory,2022,57,8.2,165,4.7,8.4
19,tm996762,Major,2022,149,9.1,7576,6.4,8.2
20,tm1209228,Norm Macdonald: Nothing Special,2022,87,7.6,1466,4.1,6.2
21,tm1204402,Ricky Gervais: SuperNature,2022,64,7.8,3256,7.5,7.4
22,ts349630,Love on the Spectrum U.S.,2022,41,8.2,1097,2.9,6.7
23,ts356951,Hurts Like Hell,2022,50,8.4,83,8.4,9.1
24,ts311989,jeen-yuhs,2022,93,8.0,8319,3.9,7.1

In [10]:
df.head()

,id,title,release_year,runtime,imdb_score,imdb_votes,tmdb_popularity,tmdb_score
0,ts89259,The Queen's Gambit,2020,56,8.6,420100,82.7,8.6
1,ts81120,The Last Dance,2020,50,9.1,115915,27.7,8.2
2,ts235758,Never Have I Ever,2020,28,7.8,47000,47.8,8.2
3,tm863808,My Octopus Teacher,2020,84,8.1,52771,19.3,8.0
4,ts219660,Alice in Borderland,2020,47,7.6,49446,71.0,8.2

In [13]:
df.describe()

,release_year,runtime,imdb_score,imdb_votes,tmdb_popularity,tmdb_score
count,25.000000,25.000000,25.000000,25.000000,25.000000,25.000000
mean,2021.200000,61.520000,8.156000,68726.320000,53.328000,7.964000
std,0.816497,27.943574,0.499233,115797.761134,78.930394,0.706447
min,2020.000000,24.000000,7.600000,83.000000,0.600000,6.200000
25%,2021.000000,47.000000,7.800000,1684.000000,6.400000,7.700000
50%,2021.000000,55.000000,8.000000,42817.000000,20.400000,8.200000
75%,2022.000000,82.000000,8.600000,77885.000000,71.000000,8.200000
max,2022.000000,149.000000,9.100000,426967.000000,361.900000,9.100000